### ISSUE TITLE
How to use our data for atomic mapping？

### ISSUE THREAD

**Issue by YH-88** [connorcoley/rexgen_direct#17]
Hi, I have tried Indigo for atom mapping, and I still get the error in preparing data step:

File "", line 29, in get_changed_bonds
[bond.GetBeginAtom().GetProp('molAtomMapNumber'),

KeyError: 'molAtomMapNumber'

Here is my code for preparing the atom mapping in indigo:
rxn = indigo.createReaction();
rxn.addReactant(mol1);
rxn.addProduct(mol2);
rxn.automap("discard");
result = rxn.smiles()

Here is my input reaction:'C(C1C(C(C(C(O1)O)O)O)O)O.NC(CCCNC(N)=N)C(O)=O>>NC(C(O)=O)CCCNC(NCC(O)=O)=N'

And here is the output of indigo: '[CH2:1]([OH:12])[CH:2]1[O:7][CH:2]([OH:7])[CH:1]([OH:12])[CH:2]([OH:7])[CH:1]1[OH:12].[NH2:13][CH:14]([C:22](=[O:24])[OH:23])[CH2:15][CH2:16][CH2:17][NH:18][C:19](=[NH:21])[NH2:20]>>[NH2:13][CH:14]([CH2:15][CH2:16][CH2:17][NH:18][C:19](=[NH:21])[NH:20][CH2:2][C:1](=[O:7])[OH:12])[C:22](=[O:24])[OH:23]'

Each atom in the product does not have a unique corresponding atom in the reactants.
Can you give me some idea about how to fix this?
In addition, what is the principle of atomic mapping in Indigo？
Thank you!

**Comment by connorcoley** [comment]
The SMILES string you've copied from Indigo doesn't look to be a valid SMILES -- it's missing many brackets. It also doesn't look like it corresponds to the reaction you've input? That will be your first problem. If you end up with a reaction where the product atoms do not appear to have come from reactant atoms, then a graph-based approach like this one that operates at the level of graph edits will be unable to describe the transformation.

Indigo uses a maximum common substructure algorithm I believe. I'm not directly familiar with its use. 

The reaction you provide does not look chemically reasonable; I could be wrong, but I can understand why a MCS tool would fail to map this:
![image](https://user-images.githubusercontent.com/4213670/97872671-6bb3d180-1ce4-11eb-9a90-15c981ddd6da.png)

**Comment by YH-88** [comment]
Thank you for your reply.
The molecular input is in the Canonical SMILES format,like this: C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O,C(CCN)CC(C(=O)O)N;
Here is the output of indigo:[CH2:1]([OH:23])[CH:2]1[O:7][CH:2]([O:7]C2[CH:2]([OH:7])[CH:1]([OH:23])C(O)[O:7][CH:2]2[CH2:1][OH:23])[CH:1]([OH:23])[CH:2]([OH:7])[CH:1]1[OH:23].[CH2:24]([CH2:28][CH:29]([NH2:33])[C:30]([OH:32])=[O:31])[CH2:25][CH2:26][NH2:27]>>[CH2:24]([CH2:28][CH:29]([NH2:33])[C:30]([OH:32])=[O:31])[CH2:25][CH2:26][NH:27][CH2:2][C:1]([OH:23])=[O:7]

Since the substructure of the reactants is uncertain, there is no unique mapping of reactant atoms in the products.Can I understand this way？

Moreover, I'm trying retraining the _**core_wln_global**_ model completely followed your notes python nntrain_direct.py --train ../data/train.txt.proc --hidden 300 --depth 3 --save_dir model-300-3-direct | tee model-300-3-direct/log.txt.What do I need to judge that the model is balanced, and then I stop manually.

What do the bold numbers below mean?
What do **NK=20** and **NK0=10** mean in _nntrain_direct_ file?

Much thanks.

**Comment by YH-88** [comment]
Thank you for your reply.
The molecular input is in the Canonical SMILES format,like this: C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O,C(CCN)CC(C(=O)O)N;
Here is the output of indigo:[CH2:1[CH:2]1[O:7][CH:2][CH:1][CH:2][CH:1]1[OH:23].[CH2:24][CH2:25][CH2:26][NH2:27]>>[CH2:24][CH2:25][CH2:26][NH:27][CH2:2][C:1]=[O:7]

Since the substructure of the reactants is uncertain, there is no unique mapping of reactant atoms in the products.Can I understand this way？

Moreover, I'm trying retraining the core_wln_global model completely followed your notes python nntrain_direct.py --train ../data/train.txt.proc --hidden 300 --depth 3 --save_dir model-300-3-direct | tee model-300-3-direct/log.txt.What do I need to judge that the model is balanced, and then I stop manually.

What do the bold numbers below mean?
What do NK=20 and NK0=10 mean in nntrain_direct file?

Much thanks.

**Comment by YH-88** [comment]
Thank you for your reply.
The molecular input is in the Canonical SMILES format,like this: C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O,C(CCN)CC(C(=O)O)N;
Here is the output of indigo:[CH2:1[CH:2]1[O:7][CH:2][CH:1][CH:2][CH:1]1[OH:23].[CH2:24][CH2:25][CH2:26][NH2:27]>>[CH2:24][CH2:25][CH2:26][NH:27][CH2:2][C:1]=[O:7]

Since the substructure of the reactants is uncertain, there is no unique mapping of reactant atoms in the products.Can I understand this way？

Moreover, I'm trying retraining the core_wln_global model completely followed your notes __python _n_ntrain_direct.py --train ../data/train.txt.proc --hidden 300 --depth 3 --save_dir model-300-3-direct | tee model-300-3-direct/log.txt.__What do I need to judge that the model is balanced, and then I stop manually.

What do the bold numbers below mean?
What do **NK=20** and **NK0=10** mean in _nntrain_direct_ file?

Much thanks.

**Comment by connorcoley** [comment]
> [CH2:1[CH:2]1[O:7][CH:2][CH:1][CH:2][CH:1]1[OH:23].[CH2:24][CH2:25][CH2:26][NH2:27]>>[CH2:24][CH2:25][CH2:26][NH:27][CH2:2][C:1]=[O:7]

That's still not a valid SMILES string, so I'm not sure why you're getting that as output from Indigo

> What do I need to judge that the model is balanced, and then I stop manually.

You can get the validation performance of each checkpoint as the notes.txt file tells you

> What do the bold numbers below mean?

NK and NK0 are used for reporting accuracies during training. NK is used to set the number of edits included in the output file during inference

**Comment by YH-88** [comment]
Thank you very much.I have a few more questions for you to help.Firstly,what do **max_nb = 10** mean in _mol_graph_ file?And can I adjust the parameter?Secondly,does the Acc@20:%.4f represent the accuracy of 20 samples in _nntrain_direct_file_ ?But does  **err** in the calculation formula mean error in **print("Acc@10: %.4f, Acc@20: %.4f, Param Norm:  %.2f, Grad Norm: %.2f" % (sum_acc / (50 * batch_size), sum_err / (50 * batch_size), pnorm, sum_gnorm / 50) )**?

**Comment by connorcoley** [comment]
max_nb is a very generous upper limit on the number of neighbors for any one atom. You can change this parameter as long as all of the atoms in the dataset have ≤ max_nb neighbors.

The accuracy in that report means that the true graph edits are the highest scored graph edits. I'm not sure I know what you're asking beyond that

**Comment by YH-88** [comment]
Thank you for your reply.
Sprry, I did not express clearly about the second question above.Does this formula, _sum_err / (50 * batch_size)_, calculate **ACC@20.%.4f**?Acc is for accuracy, err is for error? I don't quite understand the formula.
Here is another question:
When mapping the reactants as cyclic compounds, as shown in Figure 1, it can be known from the product (Figure 2) that only two carbon atoms are involved in the reaction. Indigo can be used to match the three largest common substructures in the reactants (Figure 3), resulting in the product cannot have unique mapped atoms in the reactant. Have you ever had such a situation, and can you tell me how to deal with it?
![image](https://user-images.githubusercontent.com/56984869/99207380-d1ca4980-27f8-11eb-9ee2-8307b3d73e11.png)
![image](https://user-images.githubusercontent.com/56984869/99207492-0fc76d80-27f9-11eb-931a-fd4f015278bc.png)
![image](https://user-images.githubusercontent.com/56984869/99207613-5fa63480-27f9-11eb-914e-160b6a309439.png)

**Comment by connorcoley** [comment]
Thanks for clarifying. `sum_err` is a poorly repurposed variable name. As it is used in the code, that refers to the accuracy looking at the top NK=20 predictions.

I don't quite understand what you're showing in these figures. Is there supposed to be a reaction that produces Fig 3 from Fig 2? I don't think I would consider that a valid reaction example.

**Comment by YH-88** [comment]
Much thanks for your reply.I‘m sorry for not expressing my meaning clearly.In fact,Fig 3 is one of the reactants, and Fig 2 is the product. Multiple identical substructures appear in Fig 3,  resulting in the product cannot have unique mapped atoms in the reactant.
![image](https://user-images.githubusercontent.com/56984869/99326737-6f824f00-28b3-11eb-885b-4cb18686905e.png)

**Comment by connorcoley** [comment]
I see -- I think this is a case where atom mapping software could try to map the reaction but would never do a good job. It looks very unplausible that the motif in Figure 2 comes from Figure 3. Is this a known biochemical transformation? Would you be able to link to a paper or reference?

**Comment by YH-88** [comment]
Thanks for your reply.I get it.Could you help solve the following two questions?Firstly,could you tell me why you defined **f[-4] = 1.0 if comp[i] != comp[j] else 0.0** and **f[-3] = 1.0 if comp[i] == comp[j] else 0.0** in function `**def get_bin_feature(r, max_natoms)**` in _ioutils_direct.py_?In the result, does the **f[-4] = 1.0 if comp[i] != comp[j] else 0.0**  override the result in the  BondType-**bond.IsInRing()**?
In addition,would you tell me what is the calculation principle of this formula **sp_labels.append(i * max_natoms * nbos + j * nbos + k)**in _ioutils_direct.py_?Thanks.

**Comment by connorcoley** [comment]
Yes, there is a minor indexing error that leads to a small change in the featurization; fortunately, this has a very small effect on the quantitative results themselves.

That formula is mapping indices of a 3D tensor with indices (i, j, k) and dimensions (?, max_natoms, nbos) to a 1D indexing scheme. See [here](https://coderwall.com/p/fzni3g/bidirectional-translation-between-1d-and-3d-arrays) for an example.

**Comment by YH-88** [comment]
I'm really grateful to you.I am wondering if you can share the modified code. Or could you tell me how to modify the code?Thanks a lot.

**Comment by connorcoley** [comment]
It should suffice to change `binary_fdim = 4 + bond_fdim` to `binary_fdim = 5 + bond_fdim` [here](https://github.com/connorcoley/rexgen_direct/blob/master/rexgen_direct/core_wln_global/ioutils_direct.py#L7)

**Comment by YH-88** [comment]
Thanks a lot.
